# coding=UTF-8
from adt.stack_queue.pq import PriorityQueue
if __name__ =='__main__':
    lista = PriorityQueue()

    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    #print("Tail: "+str(lista.tail.data))
    print("dequeue: "+str(lista.dequeue()))
    print("\n")
    print("enqueue: "+str(lista.enqueue(1,5)))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    print("\n")
    #print("dequeue: "+str(lista.dequeue()))

    print("enqueue: "+str(lista.enqueue(2,2)))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    print("\n")
    print("enqueue: "+str(lista.enqueue(3,3)))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    print("\n")
    print("enqueue: "+str(lista.enqueue("3")))
    print("\n")
    print("str: "+str(lista))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    print("dequeue: "+str(lista.dequeue()))
    print("\n")
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    print("str: "+str(lista))
    print("dequeue: "+str(lista.dequeue()))
    print("\n")
    print("front: "+str(lista.front()))
    #print("Tail: "+str(lista.tail.data))
    print("str: "+str(lista))
    print("dequeue: "+str(lista.dequeue()))
    print("\n")
    print("front: "+str(lista.front()))
    #print("Tail: "+str(lista.tail.data))
    print("str: "+str(lista))
    print("\n")
    print("enqueue: "+str(lista.enqueue(1,5)))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    print("\n")
    print("enqueue: "+str(lista.enqueue(2,4)))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    print("\n")
    print("enqueue: "+str(lista.enqueue("3")))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    print("\n")
    print("enqueue: "+str(lista.enqueue(3,3)))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    print("\n")
    print("enqueue: "+str(lista.enqueue(4,2)))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    print("\n")
    print("enqueue: "+str(lista.enqueue("3")))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    print("\n")

    print("enqueue: "+str(lista.enqueue(5,1)))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    print("\n")
    print("enqueue: "+str(lista.enqueue(6,1)))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    print("\n")
    print("enqueue: "+str(lista.enqueue("3")))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    print("\n")
    print("enqueue: "+str(lista.enqueue(7,1)))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    print("\n")
    print("enqueue: "+str(lista.enqueue(8,1)))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    #print(lista.prior())
    print("\n")
    print("enqueue: "+str(lista.enqueue(20,1)))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    #print(lista.prior())
    print("\n")
    print("enqueue: "+str(lista.enqueue(30,5)))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    #print(lista.prior())
    print("\n")
    print("enqueue: "+str(lista.enqueue(20,10)))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    #print(lista.prior())
    print("\n")
    print("enqueue: "+str(lista.enqueue(10,8)))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    #print(lista.prior())
    print("\n")
    print("enqueue: "+str(lista.enqueue(21,9)))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    #print(lista.prior())
    print("\n")
    print("enqueue: "+str(lista.enqueue(8,9)))
    print("str: "+str(lista))
    print("len: "+str(len(lista)))
    print("front: "+str(lista.front()))
    print("Tail: "+str(lista.tail.data))
    #print(lista.prior())
    print("\n")
#[tail,20,8,21,10,30,1,2,3,4,20,8,front]
print("dequeue: "+str(lista.dequeue()))
print("\n")
print("front: "+str(lista.front()))
print("Tail: "+str(lista.tail.data))
print("str: "+str(lista))
print("dequeue: "+str(lista.dequeue()))
print("\n")
print("front: "+str(lista.front()))
print("Tail: "+str(lista.tail.data))
print("str: "+str(lista))
print("dequeue: "+str(lista.dequeue()))
print("\n")
print("front: "+str(lista.front()))
print("Tail: "+str(lista.tail.data))
print("str: "+str(lista))
#print(lista.prior())
