from adt.graphs.graph import Graph
import math
if __name__ == '__main__':
    grafo = Graph()

    """print("insert: "+str(grafo.insertNode(0)))
    print("insert: "+str(grafo.insertNode(1)))
    print("insert: "+str(grafo.insertNode(2)))
    print("insert: "+str(grafo.insertNode(3)))
    print("insert: "+str(grafo.insertNode(4)))
    print("insert: "+str(grafo.insertNode(5)))
    print("")
    print("arist: "+str(grafo.insertArist(3,4,4)))
    print("arist: "+str(grafo.insertArist(2,4,2)))
    print("arist: "+str(grafo.insertArist(2,5,6)))
    #print("arist: "+str(grafo.insertArist(0,1,4)))
    print("arist: "+str(grafo.insertArist(2,1,4)))
    print("arist: "+str(grafo.insertArist(0,2,5)))
    print("arist: "+str(grafo.insertArist(0,3,8)))
    print("arist: "+str(grafo.insertArist(2,3,1)))
    #print("arist: "+str(grafo.insertArist(2,3,1)))
    #print("arist: "+str(grafo.insertArist(0,1)))
    print("arist: "+str(grafo.insertArist(4,5,2)))
    #print("arist: "+str(grafo.insertArist(0,"g")))
    print("arist: "+str(grafo.insertArist(3,0,3)))
    #print(grafo)

    print("")
    #print("Elimarist: "+str(grafo.deleteArist(3,0)))
    #print("Elimarist: "+str(grafo.deleteArist(0)))
    #print("Elimanode: "+str(grafo.deleteNode(None)))"""

    """print("insert: "+str(grafo.insertNode("A")))
    print("insert: "+str(grafo.insertNode("B")))
    print("insert: "+str(grafo.insertNode("C")))
    print("insert: "+str(grafo.insertNode("D")))
    print("insert: "+str(grafo.insertNode("E")))
    print("arist: "+str(grafo.insertArist("A","C",8)))
    print("arist: "+str(grafo.insertArist("A","B",4)))
    print("arist: "+str(grafo.insertArist("C","A",8)))
    print("arist: "+str(grafo.insertArist("B","A",4)))
    print("arist: "+str(grafo.insertArist("B","C",1)))
    print("arist: "+str(grafo.insertArist("C","D",4)))
    print("arist: "+str(grafo.insertArist("D","C",4)))
    print("arist: "+str(grafo.insertArist("B","D",2)))
    print("arist: "+str(grafo.insertArist("D","B",2)))
    print("arist: "+str(grafo.insertArist("C","E",2)))
    print("arist: "+str(grafo.insertArist("E","C",2)))
    print("arist: "+str(grafo.insertArist("D","E",7)))
    print("arist: "+str(grafo.insertArist("E","D",7)))"""

    """print("insert: "+str(grafo.insertNode("A")))
    print("insert: "+str(grafo.insertNode("B")))
    print("insert: "+str(grafo.insertNode("C")))
    print("insert: "+str(grafo.insertNode("D")))
    print("arist: "+str(grafo.insertArist("A","C",4)))
    print("arist: "+str(grafo.insertArist("A","B",3)))
    print("arist: "+str(grafo.insertArist("C","D",3)))
    print("arist: "+str(grafo.insertArist("D","A",8)))
    print("arist: "+str(grafo.insertArist("B","D",5)))

    print(grafo.caminosMinimos())
    print(grafo)
    ls = (1,2,3)
    print()
    """
    print("insert: "+str(grafo.insertNode(1)))
    print("insert: "+str(grafo.insertNode(2)))
    print("insert: "+str(grafo.insertNode(3)))
    print("insert: "+str(grafo.insertNode(4)))
    print("insert: "+str(grafo.insertNode(5)))
    print("")
    print("arist: "+str(grafo.insertArist(1,2,3)))
    print("arist: "+str(grafo.insertArist(1,3,8)))
    print("arist: "+str(grafo.insertArist(1,5,-4)))
    print("arist: "+str(grafo.insertArist(2,4,1)))
    print("arist: "+str(grafo.insertArist(2,5,7)))
    print("arist: "+str(grafo.insertArist(3,2,4)))
    print("arist: "+str(grafo.insertArist(4,3,-5)))
    print("arist: "+str(grafo.insertArist(4,1,2)))
    print("arist: "+str(grafo.insertArist(5,4,6)))
    print("")
    print(grafo.caminosMinimos())
